'use strict';
const KEY='csi-machine-reporting-checklist-v1';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const root=$('#app');
let state={version:1,done:{},open:{},notes:{},configs:{}};
let saveOK=true;
try{const raw=localStorage.getItem(KEY);if(raw){const p=JSON.parse(raw);if(p.version===1)state={...state,...p};}}catch(e){saveOK=false;}
const groups=[...DATA.machines,...DATA.kepware];
const tasks=new Map(groups.flatMap(g=>g.tasks.map(t=>[t.id,{...t,group:g.id}])));
const nodes=new Map();
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function html(tag,cls,content){const n=el(tag,cls);n.innerHTML=content;return n;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));saveOK=true;}catch(e){saveOK=false;}$('span#storage').textContent=saveOK?'Saved on this device':'Storage unavailable: export your progress';}
function toast(text,undo){const box=$('#toast');box.replaceChildren(el('span','',text));if(undo){const b=el('button','', 'Undo');b.type='button';b.onclick=undo;box.append(b);}box.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.hidden=true,7000);}
function download(name,text,type='text/plain;charset=utf-8'){if(name.endsWith('.scl')&&!text.startsWith('\uFEFF'))text='\uFEFF'+text;const u=URL.createObjectURL(new Blob([text],{type}));const a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function sourceLink(topic){const a=el('button','text-link','Open instructions');a.type='button';a.onclick=()=>showTopic(topic);return a;}
function details(id,title,sub='',cls='folder'){
 const d=el('details',cls);d.id=id;d.open=!!state.open[id];
 const s=el('summary');const wrap=el('span','summary-text');wrap.append(el('span','summary-title',title));if(sub)wrap.append(el('span','summary-sub',sub));s.append(wrap,el('span','count'));d.append(s);
 // Preserve the clicked summary's viewport position. No layout animation or auto-scroll.
 s.addEventListener('click',e=>{e.preventDefault();const y=s.getBoundingClientRect().top;d.open=!d.open;state.open[id]=d.open;persist();requestAnimationFrame(()=>window.scrollBy(0,s.getBoundingClientRect().top-y));});
 return d;
}
function openAncestor(n){let p=n;while(p){if(p.tagName==='DETAILS'){p.open=true;state.open[p.id]=true;}p=p.parentElement;}}
function showTopic(id){const d=document.getElementById('i-'+id);if(!d)return;openAncestor(d);persist();requestAnimationFrame(()=>{d.querySelector('summary').focus({preventScroll:true});d.scrollIntoView({block:'start',behavior:'auto'});});}
function updateCounters(){
 let done=0;
 for(const g of groups){const count=g.tasks.filter(t=>!!state.done[t.id]).length;done+=count;$('#todo-'+g.id+' > summary .count').textContent=(g.tasks.length-count)+' left';$('#done-'+g.id+' > summary .count').textContent=count+' done';const empty=$('#todo-'+g.id+' .empty');empty.hidden=count!==g.tasks.length;$('#done-'+g.id+' .empty').hidden=count!==0;}
 $('#totalText').textContent=`${done} of ${tasks.size} complete`;$('#progress').value=done;$('#progress').max=tasks.size;
 $('#programming > summary .count').textContent=(tasks.size-done)+' left';$('#completed > summary .count').textContent=done+' done';
 const kd=DATA.kepware.flatMap(g=>g.tasks).filter(t=>state.done[t.id]).length;$('#kepware > summary .count').textContent=(24-kd)+' left';$('#completed-kepware > summary .count').textContent=kd+' done';
}
function moveTask(id,complete,announce=true){
 const n=nodes.get(id);const t=tasks.get(id);if(!n||!t)return;
 // Anchor the next visible row, not a node that is about to move to another folder.
 const before=n.parentElement;const sibling=n.nextElementSibling||before.closest('details').querySelector('summary');const oldY=sibling.getBoundingClientRect().top;
 if(complete)state.done[id]=new Date().toISOString();else delete state.done[id];
 n.classList.toggle('finished',complete);$('input[type=checkbox]',n).checked=complete;$('.task-action',n).textContent=complete?'Restore':'Complete';
 const destination=$('#'+(complete?'done-':'todo-')+t.group+' .tasks');
 const order=groups.find(g=>g.id===t.group).tasks.map(x=>x.id);const next=[...destination.children].find(x=>order.indexOf(x.dataset.task)>order.indexOf(id));destination.insertBefore(n,next||null);
 updateCounters();persist();
 requestAnimationFrame(()=>{const change=sibling.getBoundingClientRect().top-oldY;if(Math.abs(change)>1)window.scrollBy(0,change);});
 if(announce)toast(complete?'Moved to Completed.':'Restored to the original checklist.',()=>moveTask(id,!complete));
}
function taskRow(t){
 const row=el('article','task');row.dataset.task=t.id;
 const line=el('div','task-line');const check=el('input');check.type='checkbox';check.id='check-'+t.id;check.setAttribute('aria-label','Complete: '+t.title);check.checked=!!state.done[t.id];check.addEventListener('change',()=>moveTask(t.id,check.checked));
 const title=el('label','task-title',t.title);title.htmlFor=check.id;const action=el('span','task-action',check.checked?'Restore':'Complete');line.append(check,title,action);row.append(line);
 const d=details('detail-'+t.id,'Details and notes','','task-detail');const body=el('div','task-body');body.append(el('p','',t.detail),sourceLink(t.topic));const lab=el('label','note-label','Your notes');const txt=el('textarea');txt.rows=2;txt.placeholder='Record what you verified. Saved only in this browser.';txt.maxLength=8000;txt.value=state.notes[t.id]||'';txt.setAttribute('aria-label',t.title+' notes');txt.addEventListener('input',()=>{state.notes[t.id]=txt.value;persist();});lab.append(txt);body.append(lab);d.append(body);row.append(d);row.classList.toggle('finished',check.checked);nodes.set(t.id,row);return row;
}
function groupFolder(g,completed=false){const d=details((completed?'done-':'todo-')+g.id,g.title,completed?'Uncheck a task to return it to Programming.':g.version||'Server configuration and read-only tags.','subfolder');const body=el('div','folder-body');if(!completed&&g.version){body.append(machineCard(g),machineConfig(g));}const list=el('div','tasks');body.append(list,el('p','empty',completed?'No completed tasks here yet.':'All tasks in this checklist are complete.'));d.append(body);return d;}
function machineCard(m){const section=el('div','machine-card');section.append(el('p','archive',m.archive),el('p','',m.family));
 const grid=el('div','signal-grid');for(const [label,value,detail] of [['Start candidate',m.start,'Servo branch only · output '+m.output],['End candidate',m.end,'From '+m.raw+' · observe low → high']]){const c=el('div','signal');c.append(el('span','small-label',label),el('code','signal-address',value),el('span','muted',detail));grid.append(c);}section.append(grid);
 section.append(el('p','callout',m.id==='MM6'?'MM6 stop gate: verify the LIVE hydraulic branch. Old load data selects Bucher. RobotInMouldNotClear is named backward relative to the traced positive permit. DB94.DBX29.4 is now a reserve input, not the end signal.':'Verify this machine independently: Servo selector DB200.DBX38.2 and EUROMAP selector DB200.DBX49.3 must match the operating trace. A duplicate project is not proof of the running mapping.'));
 if(m.id==='MM6'){const d=details('mm6-alt','Other hydraulic branch candidates','','task-detail');d.append(html('div','task-body','<p>If Bucher is the live selection, examine <code>DB93.DBX126.7</code> (fast close, FC112 NW13) and <code>DB93.DBX128.7</code> (broader close including repressing, NW14). Archived programmed outputs are Q5034.0 and Q5034.1; physical wiring is unverified. Do not adopt either automatically. If A_Line/Vickers is selected, trace that branch first.</p>'));section.append(d);}
 return section;}
function machineConfig(m){const d=details('config-'+m.id,'Machine notes and confirmed block numbers','These values stay in this browser.','task-detail');const grid=el('div','config-grid');const cfg=state.configs[m.id]||{};
 for(const [key,label,placeholder] of [['ip','Verified PLC address','Enter confirmed IP / endpoint'],['cpu','CPU / firmware','From online diagnostics'],['db','CSI_Report DB number','Actual compiled DB number'],['instance','Monitor FB / instance DB','Record assigned numbers'],['connection','Kepware model / rack / slot / TSAP','Use this device’s confirmed connection'],['signals','Auto / communication / abort mappings','Record verified source tags']]){const l=el('label','note-label',label);const input=el('input');input.type=key==='db'?'number':'text';if(key==='db'){input.min='1';input.max='65535';}input.placeholder=placeholder;input.value=cfg[key]||'';input.id='cfg-'+m.id+'-'+key;input.addEventListener('input',()=>{state.configs[m.id]??={};state.configs[m.id][key]=input.value;persist();renderMap(m.id);});l.append(input);grid.append(l);}d.append(grid);return d;}
function renderMap(machine){const box=$('#map-'+machine);if(!box)return;box.replaceChildren();const db=state.configs[machine]?.db;const valid=/^\d+$/.test(db||'')&&Number(db)>0&&Number(db)<=65535;
 const message=el('p','',valid?`Address reference for ${machine}, DB${Number(db)}. Verify every byte offset in TIA.`:'Enter the confirmed CSI_Report DB number in this machine’s Programming notes. No DB number is assumed.');box.append(message);
 const wrap=el('div','table-scroll');const table=html('table','','<thead><tr><th>Tag</th><th>Byte</th><th>Type</th><th>Kepware address</th></tr></thead>');const tb=el('tbody');for(const f of DATA.schema){const tr=el('tr');tr.title=f.description;tr.append(el('td','',f.name),el('td','',f.offset.toString()),el('td','',f.kepware),el('td','mono',valid?`DB${Number(db)},${f.type.toUpperCase()}${f.offset}`:'DB?,…'));tb.append(tr);}table.append(tb);wrap.append(table);box.append(wrap);const b=el('button','secondary','Download address reference CSV');b.type='button';b.disabled=!valid;b.onclick=()=>{const rows=[['Machine','Tag Name','Siemens Type','Byte Offset','Kepware Address','Kepware Type','Client Access','Units / Meaning'],...DATA.schema.map(f=>[machine,f.name,f.type,f.offset,`DB${Number(db)},${f.type.toUpperCase()}${f.offset}`,f.kepware,'Read Only',f.description])];download(machine+'_DB'+Number(db)+'_address_reference.csv',rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');};box.append(b,el('p','muted','This is a reference CSV. Use an export from your installed Kepware version as the actual import template.'));
}
function build(){
 const inst=details('instructions','Instructions','Step-by-step Siemens and Kepware guidance.');const ib=el('div','folder-body');
 for(const x of DATA.instructions){const d=details('i-'+x.id,x.title,x.summary,'subfolder instruction');d.append(html('div','instruction-body',x.html));ib.append(d);}inst.append(ib);root.append(inst);
 const prog=details('programming','Programming','Independent checklists for each machine and the server.');const pb=el('div','folder-body');for(const m of DATA.machines)pb.append(groupFolder(m));
 const kep=details('kepware','Kepware','MM4, MM5 and MM6 tag setup.','subfolder');const kb=el('div','folder-body');for(const g of DATA.kepware){const d=groupFolder(g);const a=details('addresses-'+g.id,'Tag address reference','Generated only from your confirmed report DB.','task-detail');const b=el('div','task-body');b.id='map-'+g.id.slice(2);a.append(b);$('.folder-body',d).prepend(a);kb.append(d);}kep.append(kb);pb.append(kep);prog.append(pb);root.append(prog);
 const done=details('completed','Completed','Finished work, grouped by its original location.');const db=el('div','folder-body');const cp=details('completed-programming','Programming','','subfolder');const cpb=el('div','folder-body');for(const m of DATA.machines)cpb.append(groupFolder(m,true));const ck=details('completed-kepware','Kepware','','subfolder');const ckb=el('div','folder-body');for(const k of DATA.kepware)ckb.append(groupFolder(k,true));ck.append(ckb);cpb.append(ck);cp.append(cpb);db.append(cp);done.append(db);root.append(done);
 const res=details('resources','Resources','Reference SCL, call recipe, source notes and offline use.');const rb=el('div','folder-body');rb.append(html('div','callout','<strong>Compilation gate:</strong> these SCL references are not TIA-compiled or machine-tested. Choose the correct pair below; verify target syntax, unused block names and retention before any download. No OB1/OB100 replacement or machine project is included.'));
 const downloads=[['CSI_Core_Legacy.scl','MM4/MM5 core reference'],['CSI_Clock_Legacy.scl','Legacy clock adapter'],['CSI_Core_1500.scl','MM6 / 1500 core reference'],['CSI_Clock_1500.scl','1500 clock adapter'],['Call_recipe.txt','Cyclic and startup call recipe']];const dl=el('div','downloads');for(const [path,title] of downloads){const a=el('button','secondary',title);a.type='button';a.onclick=()=>download(path,FILES[path]);dl.append(a);}rb.append(dl,el('p','muted','Download the matching core and clock adapter. The clock block has the same name in both versions: do not import both adapters into one PLC.'));
 const sd=details('source-notes','Evidence and official references','Archive evidence versus target-version documentation.','subfolder');const sb=html('div','instruction-body','<p>Machine addresses and insertion landmarks come from the two offline project analyses dated September 24, 2026. MM4/MM5: FC452 NW27, FC200 NW10, FC166 NW1, OB1 end after existing NW48. MM6: the same signal-path blocks with changed input/output addresses, plus OB1 NW48 RobotMain. These are not live confirmations.</p><p>The official online documentation below may describe a newer TIA/Kepware release. Use the installed V15/V16 target’s F1 help for exact syntax/support and the actual load preview for commissioning decisions.</p>');for(const s of DATA.sources){const p=el('p');p.id=s.id;const a=el('a','',s.title);a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';p.append(a);sb.append(p);}sb.append(el('p','muted','No complete customer archive, credentials or default IPs are published. Notes and progress are not uploaded to GitHub.'));
 sd.append(sb);rb.append(sd);
 rb.append(html('div','instruction-body','<h3>Using the page on site</h3><p>Open the app before leaving an internet connection. A service worker caches this app for supported browsers; check the offline indicator. Browser storage can be cleared, so export progress at milestones. Export/import transfers progress between your laptop and the Kepware PC; it is not automatic synchronization.</p><p>The standalone HTML download contains the guide and all reference source files inside it. It does not require a server for the checklist to work. Some browsers restrict local-file storage, so export progress there too.</p>'));
 const standalone=el('button','secondary','Download standalone HTML');standalone.type='button';standalone.onclick=async()=>{try{const text=await fetch('./index.html',{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error();return r.text();});download('Machine_reporting_checklist.html',text,'text/html;charset=utf-8');}catch{toast('Use your browser’s Save page command or the offline ZIP provided with the project.');}};rb.append(standalone);res.append(rb);root.append(res);
 for(const g of groups)for(const t of g.tasks){const row=taskRow(t);$('#'+(state.done[t.id]?'done-':'todo-')+g.id+' .tasks').append(row);}for(const m of DATA.machines)renderMap(m.id);updateCounters();persist();
}
function validateBackup(p){if(!p||p.version!==1||typeof p.done!=='object'||Array.isArray(p.done))throw new Error('Not a supported progress file');const out={version:1,done:{},open:{},notes:{},configs:{}};for(const [id,v]of Object.entries(p.done))if(tasks.has(id)&&typeof v==='string')out.done[id]=v.slice(0,100);for(const [id,v]of Object.entries(p.notes||{}))if(tasks.has(id)&&typeof v==='string')out.notes[id]=v.slice(0,8000);for(const m of DATA.machines){out.configs[m.id]={};for(const [k,v]of Object.entries(p.configs?.[m.id]||{}))if(['ip','cpu','db','instance','connection','signals'].includes(k)&&typeof v==='string')out.configs[m.id][k]=v.slice(0,1000);}for(const [id,v]of Object.entries(p.open||{}))if(typeof v==='boolean'&&document.getElementById(id)?.tagName==='DETAILS')out.open[id]=v;return out;}
$('#export').onclick=()=>download('machine-reporting-progress-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2),'application/json');
$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2e6)throw new Error('File is too large');const p=validateBackup(JSON.parse(await f.text()));if(!confirm('Replace progress and notes in this browser with this backup?'))return;state=p;persist();location.reload();}catch(err){toast('Import failed: '+err.message);}e.target.value='';};
$('#collapse').onclick=()=>{for(const d of $$('details')){d.open=false;state.open[d.id]=false;}persist();window.scrollTo(0,0);};
$$('[data-nav]').forEach(b=>b.onclick=()=>{const d=document.getElementById(b.dataset.nav);openAncestor(d);persist();requestAnimationFrame(()=>d.scrollIntoView({block:'start',behavior:'auto'}));});
$('#print').onclick=()=>{const open=$$('details').filter(d=>d.open).map(d=>d.id);$$('details').forEach(d=>d.open=true);window.print();$$('details').forEach(d=>d.open=open.includes(d.id));};
build();
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const n=document.getElementById(a.getAttribute('href').slice(1));if(!n)return;e.preventDefault();openAncestor(n);persist();requestAnimationFrame(()=>n.scrollIntoView({block:'start',behavior:'auto'}));});
// Offline support is scoped to this repo. No API calls, analytics, PLC communication or telemetry.
if('serviceWorker' in navigator && /^https?:$/.test(location.protocol)){
 navigator.serviceWorker.register('./sw.js').then(async reg=>{await navigator.serviceWorker.ready;$('#offline').textContent=navigator.onLine?'Offline cache available':'Offline copy';}).catch(()=>$('#offline').textContent='Standalone download available');
}else{$('#offline').textContent='Standalone mode';}
