'use strict';
const KEY='csi-machine-reporting-checklist-v3', OLD='csi-machine-reporting-checklist-v1';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const groups=[...DATA.groups,...DATA.kepware], tasks=new Map(groups.flatMap(g=>g.tasks.map((t,i)=>[t.id,{...t,group:g.id,number:i+1}])));
const nodes=new Map();let storageOK=true;
const obj=x=>x&&typeof x==='object'&&!Array.isArray(x);
function strings(x,max=8000){const o={};if(obj(x))for(const [k,v]of Object.entries(x))if(!['__proto__','constructor','prototype'].includes(k)&&typeof v==='string')o[k]=v.slice(0,max);return o;}
function clean(p){if(!obj(p)||p.version!==3)throw Error('Not a checklist backup');const s={version:3,done:strings(p.done,100),notes:strings(p.notes),fields:{},open:{},legacy:obj(p.legacy)?p.legacy:null};if(obj(p.fields))for(const g of groups)s.fields[g.id]=strings(p.fields[g.id],1000);if(obj(p.open))for(const [k,v]of Object.entries(p.open))if(typeof v==='boolean'&&!['__proto__','constructor','prototype'].includes(k))s.open[k]=v;return s;}
function migrate(old){const s={version:3,done:{},notes:{},fields:{},open:{programming:true,'todo-MM6':true},legacy:old};for(const id of tasks.keys()){if(old.done?.[id])s.done[id]=String(old.done[id]);if(old.notes?.[id])s.notes[id]=String(old.notes[id]);}return s;}
let state={version:3,done:{},notes:{},fields:{},open:{programming:true,'todo-MM6':true},legacy:null};
try{const cur=localStorage.getItem(KEY);if(cur)state=clean(JSON.parse(cur));else{const prev=localStorage.getItem(OLD);if(prev)state=migrate(JSON.parse(prev));}}catch{storageOK=false;}
function e(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function fragment(markup){const n=e('div','how-body');n.innerHTML=markup;return n;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}$('#saved').textContent=storageOK?'Saved in this browser':'Export progress: browser storage is unavailable';}
function toast(message,undo){const n=$('#toast');n.replaceChildren(e('span','',message));if(undo){const b=e('button','','Undo');b.onclick=undo;n.append(b);}n.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.hidden=true,6000);}
function download(name,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=e('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Copied.');}catch{toast('Clipboard is unavailable here. Select and copy the visible text.');}}
function folder(id,title,cls='folder',hint=''){const d=e('details',cls);d.id=id;d.open=!!state.open[id];const s=e('summary');const label=e('span','summary-label');label.append(e('span','title',title));if(hint)label.append(e('span','hint',hint));s.append(label,e('span','count'));d.append(s);return d;}
function reveal(id){const n=document.getElementById(id);if(!n)return;let p=n;while(p){if(p.tagName==='DETAILS'){p.open=true;state.open[p.id]=true;}p=p.parentElement;}save();requestAnimationFrame(()=>n.scrollIntoView({block:'start',behavior:'auto'}));}
function groupBox(g,complete=false){const d=folder((complete?'done-':'todo-')+g.id,g.title,'group',complete?'':g.hint);const list=e('div','task-list');d.append(list,e('p','empty',complete?'No completed steps.':'All steps completed.'));return d;}
function taskNode(t){const row=e('article','task');row.dataset.task=t.id;const top=e('div','task-top');const check=e('input');check.type='checkbox';check.id='check-'+t.id;check.checked=!!state.done[t.id];check.setAttribute('aria-label','Complete: '+t.title);check.onchange=()=>move(t.id,check.checked);const number=e('span','step-number',String(t.number).padStart(2,'0'));const label=e('label','task-title',t.title);label.htmlFor=check.id;top.append(check,number,label);row.append(top);
const how=folder('how-'+t.id,'How','how');const body=fragment(t.body);how.append(body);row.append(how);
if(t.watch){const code=e('pre');code.textContent=t.watch.join('\n');const b=e('button','small-button','Copy tag names');b.onclick=()=>copyText(code.textContent);body.append(code,b);}
if(t.fields){for(const [key,label,type]of t.fields){const wrap=e('label','field',label);const input=e('input');input.type=type;input.id='field-'+t.group+'-'+key;input.value=state.fields[t.group]?.[key]||'';input.maxLength=1000;if(type==='number'){input.min='1';input.max='65535';}input.oninput=()=>{state.fields[t.group]??={};state.fields[t.group][key]=input.value;save();if(key==='reportDbV2')renderMap();};wrap.append(input);body.append(wrap);}}
if(t.map){const map=e('div');map.id='tag-map';body.append(map);}
const note=folder('note-'+t.id,'Notes','notes');const text=e('textarea');text.rows=2;text.maxLength=8000;text.placeholder='Your result or the exact tag name';text.value=state.notes[t.id]||'';text.setAttribute('aria-label',t.title+' notes');text.oninput=()=>{state.notes[t.id]=text.value;save();};note.append(text);body.append(note);
row.classList.toggle('finished',check.checked);nodes.set(t.id,row);return row;}
function counts(){let total=0;for(const g of groups){const done=g.tasks.filter(t=>state.done[t.id]).length;total+=done;$('#todo-'+g.id+' > summary .count').textContent=(g.tasks.length-done)+' left';$('#done-'+g.id+' > summary .count').textContent=String(done);$('#todo-'+g.id+' > .empty').hidden=done!==g.tasks.length;$('#done-'+g.id+' > .empty').hidden=done!==0;}$('#progress-text').textContent=total+' / '+tasks.size+' done';$('#progress').max=tasks.size;$('#progress').value=total;$('#completed > summary .count').textContent=String(total);}
function move(id,value,notify=true){const n=nodes.get(id),t=tasks.get(id);const anchor=n.nextElementSibling||n.parentElement.parentElement.querySelector('summary');const y=anchor.getBoundingClientRect().top;if(value)state.done[id]=new Date().toISOString();else delete state.done[id];const dest=$('#'+(value?'done-':'todo-')+t.group+' > .task-list');const next=[...dest.children].find(x=>tasks.get(x.dataset.task).number>t.number);dest.insertBefore(n,next||null);$('input[type=checkbox]',n).checked=value;n.classList.toggle('finished',value);counts();save();requestAnimationFrame(()=>{window.scrollBy(0,anchor.getBoundingClientRect().top-y);});if(notify)toast(value?'Moved to Completed.':'Restored to its checklist.',()=>move(id,!value));}
function renderMap(){const box=$('#tag-map');if(!box)return;const db=state.fields.MM6?.reportDbV2||'';const valid=/^[0-9]+$/.test(db)&&Number(db)>=1&&Number(db)<=65535;box.replaceChildren();const label=e('label','field','CSI2_Report DB number (enter it, then press Tab)');const input=e('input');input.type='number';input.min='1';input.max='65535';input.value=db;input.id='kepware-db';label.append(input);box.append(label);input.addEventListener('change',()=>{state.fields.MM6??={};state.fields.MM6.reportDbV2=input.value;const other=$('#field-MM6-reportDbV2');if(other)other.value=input.value;save();renderMap();});box.append(e('p','muted',valid?'Verify these offsets in CSI2_Report before entering the tags.':'Enter the new CSI2_Report DB number. No old DB number is reused automatically.'));
function addTable(fields,parent){const wrap=e('div','table-wrap');const tab=e('table');const head=e('thead');const tr=e('tr');['Name','Type','Byte','Kepware address'].forEach(v=>tr.append(e('th','',v)));head.append(tr);tab.append(head);const body=e('tbody');for(const f of fields){const r=e('tr');r.append(e('td','',f.name),e('td','',f.kepware_type),e('td','',String(f.offset)));const c=e('td','address');const a=valid?`DB${Number(db)},${f.type.toUpperCase()}${f.offset}`:'Enter DB number';c.append(e('code','',a));r.append(c);body.append(r);}tab.append(body);wrap.append(tab);parent.append(wrap);}
addTable(DATA.display_fields.map(n=>DATA.schema.find(f=>f.name===n)),box);const quality=folder('quality-map','Quality, status and period identifiers','small');addTable(DATA.schema.filter(f=>!DATA.display_fields.includes(f.name)),quality);box.append(quality);const button=e('button','small-button','Download complete address reference');button.disabled=!valid;button.onclick=()=>{const rows=[['Tag','Address','Type','Client access','Meaning'],...DATA.schema.map(f=>[f.name,`DB${Number(db)},${f.type.toUpperCase()}${f.offset}`,f.kepware_type,'Read Only',f.description])];download('MM6_CSI2_Report_DB'+Number(db)+'_reference.csv',rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');};box.append(button,e('p','muted','Reference CSV, not a Kepware-version-specific import file. Times are REAL seconds.'));}
function legacyRecords(parent){if(!state.legacy)return;const d=folder('legacy-records','Earlier checklist records','group');d.append(e('p','muted','Saved checks, notes and DB numbers from the longer guide. MM6 V2 installation steps start unchecked; the old report DB is not assumed to be CSI2_Report.'));
for(const g of groups){const ids=new Set([...Object.keys(state.legacy.done||{}),...Object.keys(state.legacy.notes||{})].filter(k=>k.startsWith(g.id+'-')&&!tasks.has(k)));const config=state.legacy.configs?.[g.id];if(!ids.size&&!obj(config))continue;const sub=folder('legacy-'+g.id,g.title,'small');for(const id of ids){const card=e('div','legacy-row');card.append(e('strong','',(state.legacy.done?.[id]?'Completed: ':'Note: ')+id),e('p','',String(state.legacy.notes?.[id]||'')));sub.append(card);}if(obj(config)){const pre=e('pre');pre.textContent=JSON.stringify(config,null,2);sub.append(pre);}d.append(sub);}parent.append(d);}
function build(){const app=$('#app');const inst=folder('instructions','Instructions');for(const x of DATA.instructions){const d=folder('i-'+x.id,x.title,'group');d.append(fragment(x.body));inst.append(d);}app.append(inst);
const prog=folder('programming','Programming');DATA.groups.forEach(g=>prog.append(groupBox(g)));const kp=folder('kepware','Kepware','group');DATA.kepware.forEach(g=>kp.append(groupBox(g)));prog.append(kp);app.append(prog);
const done=folder('completed','Completed');const dp=folder('completed-programming','Programming','group');DATA.groups.forEach(g=>dp.append(groupBox(g,true)));const dk=folder('completed-kepware','Kepware','group');DATA.kepware.forEach(g=>dk.append(groupBox(g,true)));dp.append(dk);done.append(dp);legacyRecords(done);app.append(done);
for(const t of tasks.values())$('#'+(state.done[t.id]?'done-':'todo-')+t.group+' > .task-list').append(taskNode(t));renderMap();counts();save();
}
document.addEventListener('click',ev=>{const s=ev.target.closest('summary');if(s&&s.parentElement.tagName==='DETAILS'){ev.preventDefault();const d=s.parentElement,y=s.getBoundingClientRect().top;d.open=!d.open;if(d.id)state.open[d.id]=d.open;save();requestAnimationFrame(()=>window.scrollBy(0,s.getBoundingClientRect().top-y));return;}const dl=ev.target.closest('[data-source]');if(dl){ev.preventDefault();download('MM6_Reporting_V2.scl',SOURCE);return;}const nav=ev.target.closest('[data-open]');if(nav)reveal(nav.dataset.open);});
$('#export').onclick=()=>download('machine-checklist-progress.json',JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2),'application/json');
$('#import').onchange=async ev=>{const f=ev.target.files[0];if(!f)return;try{if(f.size>3e6)throw Error('File too large');const p=JSON.parse(await f.text());const next=p.version===1?migrate(p):clean(p);if(!confirm('Replace this browser’s checklist with the selected backup?'))return;state=next;save();location.reload();}catch(err){toast('Import failed: '+err.message);}ev.target.value='';};
$('#collapse').onclick=()=>{$$('details').forEach(d=>{d.open=false;if(d.id)state.open[d.id]=false;});save();window.scrollTo(0,0);};
$('#refresh').onclick=async()=>{try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration();await reg?.update();}location.reload();}catch{location.reload();}};
build();
// Exposed only for offline browser regression tests. No network/PLC API.
window.checklistTest={migrate,clean,build:DATA.build};
if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(()=>navigator.serviceWorker.ready).catch(()=>{});
