from pathlib import Path
import json
from field_steps import apply
R=Path(__file__).parent
D=apply(json.loads((R/'content.json').read_text()))
(R/'content.json').write_text(json.dumps(D, ensure_ascii=False, indent=2))
files={p.name:p.read_text(encoding='utf-8-sig') for p in (R/'downloads').iterdir() if p.is_file()}
def jsdata(x):return json.dumps(x,ensure_ascii=False).replace('</','<\\/')
text='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#142e3d"><meta name="description" content="Siemens MM4, MM5, MM6 production reporting and Kepware commissioning checklist."><title>Machine reporting · Commissioning checklist</title><link rel="manifest" href="./manifest.webmanifest"><style>'''+(R/'style.css').read_text()+'''</style></head><body>
<header><div class="head-inner"><div class="topline"><div><p class="eyebrow">Siemens + Kepware / Field guide</p><h1>Machine reporting</h1></div><span class="badge">MM4 · MM5 · MM6</span></div><p class="lead">Build the reporting logic, verify it on each machine, and bring the readings into Kepware.</p><div class="progress-area"><span id="totalText">Loading checklist…</span><progress id="progress" value="0" max="84" aria-label="Checklist completion"></progress></div></div></header>
<main><div class="toolbar"><button class="nav" type="button" onclick="showTopic(\'watch-MM5\')">MM5: start here</button><button class="nav" data-nav="instructions">Instructions</button><button class="nav" data-nav="programming">Programming</button><button class="nav" data-nav="completed">Completed</button><span class="spacer"></span><button id="export">Export progress</button><label class="import-button" for="import">Import<input id="import" type="file" accept="application/json,.json" hidden></label><button id="collapse">Collapse all</button><button id="print">Print</button></div><div class="statusbar"><span id="storage">Local browser storage</span><span id="offline">Checking offline support…</span></div><p class="intro">Open only what you need. Each machine has its own checklist. Finished tasks move to Completed, where you can restore them. No connection to your PLCs is made by this page.</p><div id="app"></div><noscript>Enable JavaScript to use the checklist. No scripts are loaded from third-party services.</noscript></main>
<footer class="footer"><div>Guide updated September 25, 2026 · Explicit watch-table steps · Reference code requires target compilation and commissioning · Progress and machine notes stay in this browser.</div></footer><div id="toast" role="status" aria-live="polite" hidden></div><script>const DATA='''+jsdata(D)+';const FILES='+jsdata(files)+';\n'+(R/'app.js').read_text()+'''</script></body></html>'''
(R/'index.html').write_text(text)
(R/'manifest.webmanifest').write_text(json.dumps({'name':'Machine reporting checklist','short_name':'Reporting','start_url':'./','scope':'./','display':'standalone','background_color':'#f1f5f6','theme_color':'#142e3d','icons':[{'src':'icon.svg','sizes':'any','type':'image/svg+xml','purpose':'any'}]},indent=2))
(R/'icon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192"><rect width="192" height="192" rx="38" fill="#142e3d"/><path d="M48 57h96M48 96h96M48 135h96" stroke="#74c8b8" stroke-width="12" stroke-linecap="round"/><path d="m42 53 7 7 15-16m-22 48 7 7 15-16m-22 48 7 7 15-16" fill="none" stroke="white" stroke-width="7"/></svg>')
(R/'sw.js').write_text('''const CACHE='machine-reporting-v2-watch-steps';
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(c=>c.addAll(['./','./index.html','./manifest.webmanifest','./icon.svg'])).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('machine-reporting-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET'||new URL(event.request.url).origin!==self.location.origin)return;event.respondWith(fetch(event.request).then(response=>{if(response.ok){const clone=response.clone();caches.open(CACHE).then(c=>c.put(event.request,clone));}return response;}).catch(()=>caches.match(event.request).then(cached=>cached||(event.request.mode==='navigate'?caches.match('./index.html'):Response.error()))));});''')
(R/'.nojekyll').write_text('')
print('HTML bytes',len(text.encode()))
